### ISSUE TITLE
[QUESTION] Do you know MidiSmtpServer?

### ISSUE THREAD

**Issue by TomFreudenberg** [mocktools/ruby-smtp-mock#37]
Hi,

I am wondering if you know the ruby library?

Maybe it is easier to integrate while using ruby instead controlling a separate process.

You are welcome for any questions.

Cheers
Tom

**Comment by bestwebua** [comment]
@TomFreudenberg I don't see any problem with controlling a separate process. I have no desire to customize third party library. I'm using [specialized tool](https://github.com/mocktools/go-smtp-mock) under the hood that coveres all needed features.

**Comment by TomFreudenberg** [comment]
Thanks for your feedback!

Stay well
Tom
